-------

### Ejercicio 1:

Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. 
Llenado por filas (1,2,3,4...).

In [1]:
import numpy as np
nums = np.arange(1,65)
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

In [2]:
mat = nums.reshape(8,8)
mat

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

-------

### Ejercicio 2:

i. Hacer una matriz de 8 x 8 con numeros enteros consecutivos empezando en 1. 
Llenado por columnas. 

ii. reemplazar los elementos que tengan al menos un 3 por -99.  

In [3]:
mat2 = mat.T
mat2

array([[ 1,  9, 17, 25, 33, 41, 49, 57],
       [ 2, 10, 18, 26, 34, 42, 50, 58],
       [ 3, 11, 19, 27, 35, 43, 51, 59],
       [ 4, 12, 20, 28, 36, 44, 52, 60],
       [ 5, 13, 21, 29, 37, 45, 53, 61],
       [ 6, 14, 22, 30, 38, 46, 54, 62],
       [ 7, 15, 23, 31, 39, 47, 55, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64]])

In [4]:
x = mat2.reshape(1,64)

In [5]:
for i in x[0]:
    if '3' in str(i):
        print(i)

33
34
3
35
43
36
13
37
53
30
38
23
31
39
63
32


In [6]:
new = []
for i in x[0]:
    if '3' in str(i):
        i = -99
    new.append(i)

In [7]:
mat3 = np.array(new).reshape(8,8)
mat3

array([[  1,   9,  17,  25, -99,  41,  49,  57],
       [  2,  10,  18,  26, -99,  42,  50,  58],
       [-99,  11,  19,  27, -99, -99,  51,  59],
       [  4,  12,  20,  28, -99,  44,  52,  60],
       [  5, -99,  21,  29, -99,  45, -99,  61],
       [  6,  14,  22, -99, -99,  46,  54,  62],
       [  7,  15, -99, -99, -99,  47,  55, -99],
       [  8,  16,  24, -99,  40,  48,  56,  64]])

-------

### Ejercicio 3:

i. Reproducir la matriz B: 

[[0.4  0.41 0.42 0.43 0.44]\
[0.45 0.46 0.47 0.48 0.49]\
[0.5  0.51 0.52 0.53 0.54]\
[0.55 0.56 0.57 0.58 0.59]\
[0.6  0.61 0.62 0.63 0.64]\
[0.65 0.66 0.67 0.68 0.69]\
[0.7  0.71 0.72 0.73 0.74]\
[0.75 0.76 0.77 0.78 0.79]]

ii. Unir B con el resultado del ejercicio anterior 2.ii para obtener una matriz de 8 lineas y 13 columnas. 

iii. Agregar una linea al final con el promedio de cada columna

iv. Agregar una columna al final con el valor maximo de cada fila

In [8]:
B = np.arange(0.4,0.8,0.01).reshape(8,5)

print('B = \n', B)

B = 
 [[0.4  0.41 0.42 0.43 0.44]
 [0.45 0.46 0.47 0.48 0.49]
 [0.5  0.51 0.52 0.53 0.54]
 [0.55 0.56 0.57 0.58 0.59]
 [0.6  0.61 0.62 0.63 0.64]
 [0.65 0.66 0.67 0.68 0.69]
 [0.7  0.71 0.72 0.73 0.74]
 [0.75 0.76 0.77 0.78 0.79]]


In [9]:
C = np.concatenate((mat3, B), axis=1)
C

array([[  1.  ,   9.  ,  17.  ,  25.  , -99.  ,  41.  ,  49.  ,  57.  ,
          0.4 ,   0.41,   0.42,   0.43,   0.44],
       [  2.  ,  10.  ,  18.  ,  26.  , -99.  ,  42.  ,  50.  ,  58.  ,
          0.45,   0.46,   0.47,   0.48,   0.49],
       [-99.  ,  11.  ,  19.  ,  27.  , -99.  , -99.  ,  51.  ,  59.  ,
          0.5 ,   0.51,   0.52,   0.53,   0.54],
       [  4.  ,  12.  ,  20.  ,  28.  , -99.  ,  44.  ,  52.  ,  60.  ,
          0.55,   0.56,   0.57,   0.58,   0.59],
       [  5.  , -99.  ,  21.  ,  29.  , -99.  ,  45.  , -99.  ,  61.  ,
          0.6 ,   0.61,   0.62,   0.63,   0.64],
       [  6.  ,  14.  ,  22.  , -99.  , -99.  ,  46.  ,  54.  ,  62.  ,
          0.65,   0.66,   0.67,   0.68,   0.69],
       [  7.  ,  15.  , -99.  , -99.  , -99.  ,  47.  ,  55.  , -99.  ,
          0.7 ,   0.71,   0.72,   0.73,   0.74],
       [  8.  ,  16.  ,  24.  , -99.  ,  40.  ,  48.  ,  56.  ,  64.  ,
          0.75,   0.76,   0.77,   0.78,   0.79]])

In [10]:
mean_col = np.mean(C, axis=0)
mean_col

array([ -8.25 ,  -1.5  ,   5.25 , -20.25 , -81.625,  26.75 ,  33.5  ,
        40.25 ,   0.575,   0.585,   0.595,   0.605,   0.615])

In [11]:
#np.insert(C, -1, mean_col, axis=0)
D = np.append(C, mean_col.reshape(1,13), axis = 0)

In [12]:
max_fila = np.max(D, axis=1)
max_fila

array([57.  , 58.  , 59.  , 60.  , 61.  , 62.  , 55.  , 64.  , 40.25])

In [13]:
E = np.append(D, max_fila.reshape(9,1), axis = 1)

In [14]:
E

array([[  1.   ,   9.   ,  17.   ,  25.   , -99.   ,  41.   ,  49.   ,
         57.   ,   0.4  ,   0.41 ,   0.42 ,   0.43 ,   0.44 ,  57.   ],
       [  2.   ,  10.   ,  18.   ,  26.   , -99.   ,  42.   ,  50.   ,
         58.   ,   0.45 ,   0.46 ,   0.47 ,   0.48 ,   0.49 ,  58.   ],
       [-99.   ,  11.   ,  19.   ,  27.   , -99.   , -99.   ,  51.   ,
         59.   ,   0.5  ,   0.51 ,   0.52 ,   0.53 ,   0.54 ,  59.   ],
       [  4.   ,  12.   ,  20.   ,  28.   , -99.   ,  44.   ,  52.   ,
         60.   ,   0.55 ,   0.56 ,   0.57 ,   0.58 ,   0.59 ,  60.   ],
       [  5.   , -99.   ,  21.   ,  29.   , -99.   ,  45.   , -99.   ,
         61.   ,   0.6  ,   0.61 ,   0.62 ,   0.63 ,   0.64 ,  61.   ],
       [  6.   ,  14.   ,  22.   , -99.   , -99.   ,  46.   ,  54.   ,
         62.   ,   0.65 ,   0.66 ,   0.67 ,   0.68 ,   0.69 ,  62.   ],
       [  7.   ,  15.   , -99.   , -99.   , -99.   ,  47.   ,  55.   ,
        -99.   ,   0.7  ,   0.71 ,   0.72 ,   0.73 ,   0.74 ,  55.   ],